{% set name = "pygbif" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygbif-{{ version }}.tar.gz
  sha256: 9b46a249314c7bc575a511428700108404e0459bd08b9789d4eb793ed90bd276

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - requests >2.7
    - requests-cache
    - geojson-rewind
    - geomet
    - appdirs >=1.4.3
    - matplotlib-base

test:
  imports:
    - pygbif
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/gbif/pygbif
  summary: Python client for GBIF
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
